# ========== GLOBAL ==========
[agent]
  interval = "3s"
  flush_interval = "3s"
  omit_hostname = false

###############################################################################
# ▶️ 从 MQTT 订阅 mem 数据（格式为 Telegraf JSON）
###############################################################################
[[inputs.mqtt_consumer]]
  servers = ["tcp://192.168.0.81:1883"]
  topics = ["furnace/writer"]
  client_id = "fuxing-s7-sub"
  data_format = "json"
  username= "fuxing"
  password= "fuxing"
  qos = 2
  persistent_session=true
  json_name_key = "name"
  tag_keys = ["tags.host"]
  json_time_key = "timestamp"
  json_time_format = "unix"



  ###############################################################################
  # ▶️ 输出到 stdout（调试用，可删）
  ###############################################################################
  [[outputs.file]]
    files = ["stdout"]
    data_format = "influx"

 [[outputs.s7comm]]
   address = "192.168.0.6:102"
   rack = 0
   slot = 1
   s7_timeout = "5s"
   ack_topic = "furnace/ack"
   syn_field = "syn"
   servers = ["tcp://192.168.0.81:1883"]
   timeout="10s"
   qos = 2
   client_id = "fuxing-s7-ack"
   username = "fuxing"
   password = "fuxing"

   [[outputs.s7comm.metric]]
     name = "s7comm"
     fields = [
        #{ name="fields_op_count", address="DB5.LI30"    },
        #{ name="fields_radio", address="DB2.R50"    },
        { name="fields_xSwitchOn",   address="DB1.X0.0" },
     ]